#http://localhost:8085/arbitrage

spring:
  application:
    name: turboBot
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085

# --- Credentials & Logic ---
msport:
  username: "08141792738"
  password: "Victor?!$#070"
  headless: true

sporty:
  username: "08141792738"
  password: "Victor?!$#070"
  headless: true

bet9ja:
  username: "Emeritus19"
  password: "Edwardkufre123"
  headless: false

# Combined ARB section to prevent "duplicate key" error
arb:
  polling:
    enabled: true
    interval:
      ms: 5000
    initial:
      delay:
        ms: 10000
    freshness:
      seconds: 2
    min:
      profit: 5
    bookmakers: SPORTYBET,MSPORT,BET9JA

fetch:
  enabled:
    football: true
    basketball: true
    table-tennis: true

playwright:
  enabled: false

# Combined Breaking-Bet section
breaking-bet:
  api:
    prematch:
      url: "https://arbs.prematch.api.breaking-bet.com/v1/users/bb-50810/filter/items"
    live:
      url: "https://arbs.live.api.breaking-bet.com/v1/users/bb-50810/filter/items"
  headless: true
  connection:
    timeout: 30
  read:
    timeout: 30
  write:
    timeout: 30
  bearer:
    token: "eyJhbGciOiJIUzI1NiJ9.eyJib29rbWFrZXJzIjpbODMsODYsMjEsNzksODIsNTMsMzksMzMsNDksOTQsOTMsMzYsODUsNzcsNiw4NCwzMSwxMCw5Miw4OSwyMyw0OCwzLDc0LDkxLDYyLDU2LDE2LDE0LDI1LDU3LDE1LDg3LDQxLDgsNTUsOTUsNjgsODAsNSw0MCw3Niw1MiwzOCw5MCw1NCw3LDksNjcsMzAsNjUsNDMsODgsNzEsNTEsMTgsMTksMjgsNCw0NF0sImV4cCI6MTc3MDEwOTQzNiwicmVzIjpbImFyYnNfcHJlbWF0Y2hfZ3Vlc3QiLCJhcmJzX2xpdmVfZ3Vlc3QiLCJ2YWx1ZWJldHNfcHJlbWF0Y2hfZ3Vlc3QiLCJ2YWx1ZWJldHNfbGl2ZV9ndWVzdCIsIm1pZGRsZXNfbGl2ZV9ndWVzdCIsIm1pZGRsZXNfcHJlbWF0Y2hfZ3Vlc3QiXSwidXNlciI6eyJpZCI6ImI2YzhjZTYyZjkxMTMwYTUzZTk0MDA0MTE3MDBhM2I3ZTBkM2ViNzgifX0.O5w-Des7rgUUl2O05tKbFzmx80H3iB8bwVcr2JQhr38"